-- TP2
-- Date : 22/11/2024
-- Auteurs : Théo COUERBE

/* Q2 */
SELECT ENOM, GNOM, LIVRES_VENDUS
FROM ECRIVAIN 
JOIN GENRE 
ON ECRIVAIN.GENRE_ID = GENRE.IDGENRE
ORDER BY (GNOM);

/* Q3 */
SELECT PNOM, ENOM, GNOM, LNOM
FROM ECRIVAIN
JOIN GENRE ON ECRIVAIN.GENRE_ID = GENRE.IDGENRE
JOIN LOCALISATION ON GENRE.LOC_ID = LOCALISATION.IDLOC;

/* Q4 */
/* Certaines données, par exemple GENRE_ID ont pour valeur (null) dans la table.
    Elles sont donc affichées lorsque l'on demande la table entière mais pas si
    on fait une requête qui requière l'ID_GENRE.
*/

/* Q5 */
SELECT PNOM, ENOM, IF (GENRE.LOC_ID = NULL) THEN "nul" ELSE LNOM;
FROM ECRIVAIN
JOIN GENRE ON NVL(ECRIVAIN.GENRE_ID, 10) = GENRE.IDGENRE
JOIN LOCALISATION ON NVL(GENRE.LOC_ID, 1) = LOCALISATION.IDLOC;



SELECT COALESCE(VALEUR, 10) FROM ECRIVAIN;











SELECT * FROM LOCALISATION;
SELECT * FROM GENRE;
SELECT * FROM ECRIVAIN;

DESC LOCALISATION;
