/* Q1 -- Mode AUTOCOMMIT ON */
SET AUTOCOMMIT ON;

/* Q2 */
CREATE TABLE ECRIVAIN AS SELECT * FROM SYS.ECRIVAIN;

SELECT * FROM ECRIVAIN;
/* Q3 */
ALTER TABLE ECRIVAIN ADD PRIMARY KEY (idecr);

/* Q4 */
INSERT INTO ECRIVAIN 
VALUES (7000, 'Hugo', 'Victor', 'H', to_date('26/09/1802', 'dd/mm/yyyy'), 'France', NULL, 1000000, NULL, 60);